<?php

const PDF_OBJECT_NULL = -1;
const PDF_OBJECT_BLOCK = 0;
const PDF_OBJECT_BOOLEAN = 4;
const PDF_OBJECT_STRING = 3;
const PDF_OBJECT_NAME = 6;
const PDF_OBJECT_ARRAY = 2;
const PDF_OBJECT_DICTIONARY = 1;
const PDF_OBJECT_NUMERIC = 5;
const PDF_OBJECT_STREAM = 7;
const PDF_OBJECT_TEXT_BLOCK = 8;
const PDF_OBJECT_TEXT_COMMAND = 9;
const PDF_OBJECT_CHAR = 10;
